### ISSUE TITLE
SDPi 1.0 - Final Update Tasks for Publication to DEV Internal Review

### ISSUE THREAD

**Issue by ToddCooper** [IHE/sdpi-fhir#230]
The following list of subtasks chart the course for finalizing the SDPi 1.0 publication to DEV Internal review:

- [x] #130  Review / Approval / Merge (focus on all that is not TF-2) - top priority task given the extensive changes!
- [x] (KR DG PK) PR #182  Review / Approval Merge
- [x] #231
- [x] #232
- [x] (DG) Reference text substitution not working in section headers (see also #229 )
- [x] #233
- [x] #234
- [x] #235
- [x] #236

**Comment by ToddCooper** [comment]
Tasks completed with the branching of [sdpi-1.0-dev-internal-review-v1](https://github.com/IHE/sdpi-fhir/tree/sdpi-1.0-dev-internal-review-v1).
